🔊 [INTL-4928] Add log for order paided cancelled
onatera/payum-dalenys-plugin pull request #5
Opened 2023-11-06 11:02 UTC by cboutinon

https://onatera.atlassian.net/browse/INTL-4928

2023-11-06 13:23 UTC, benjamin-vauchel approved these changes

2023-11-06 13:24 UTC, cboutinon commented on src/Controller/NotifyController.php
> +        if ($request->query->get('EXECCODE') !== '0000' && ($order->getPaymentState() === Payment::STATE_CANCELLED || $order->getState() === Order::STATE_CANCELLED)) {
=== pardon

2023-11-07 13:17 UTC, jum4 requested changes

2023-11-07 13:17 UTC, jum4 commented on src/Controller/NotifyController.php
> +        if ($request->query->get('EXECCODE') === '0000' && ($order->getPaymentState() === Payment::STATE_CANCELLED || $order->getState() === Order::STATE_CANCELLED)) {
Il me semble que tu peux utiliser la constante  `Payum\Api::EXECCODE_SUCCESSFUL` au lieu de directement `'0000'`

2023-11-07 13:17 UTC, jum4 commented on src/Controller/NotifyController.php
> +use Symfony\Component\HttpKernel\Log\Logger;
Je n'ai pas l'impression que ces `use` soient utilisés

2023-11-09 13:25 UTC, merged